# Generated by Django 5.2.4 on 2025-07-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djboard', '0003_answer_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
